spring.application.name=surakshapay-backend

# Server Port
server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/surakshapay?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configurations (Dummy secret for demo purposes)
jwt.secret=5Urak5haPaySup3rS3cr3tKeyF0rJWTT0kenG3n3rat10nA1B2C3D4E5F6
jwt.expiration=86400000
